import { Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: any }) {
  return (
    <html lang="en">
      <body className={`${manrope.className} relative`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
